version: '3'

services:
  asterisk:
    image: asterisk-16-ari:latest
    restart: unless-stopped
    container_name: asterisk
    ports:
      - "5061:5061"
      - "8443:8443"
      - "8080:8080"
    environment:
      - TRUNK_TYPE
      - TRUNK_ACCOUNT
      - TRUNK_PASSWORD
      - SIP_REGISTRAR
      - ARI_USER
      - ARI_PASSWORD
      - ARI_APPLICATION

  bridge:
    build:
      context: asterisk-dialogflow-ari-bridge
    restart: unless-stopped
    container_name: bridge
    depends_on:
      - "asterisk"
      - "audioserver"
    volumes:
      - ./bridge-config:/app/config

  audioserver:
    build:
      context: asterisk-dialogflow-rtp-audioserver
    restart: unless-stopped
    container_name: audioserver
    ports:
      - "7777:7777"
    depends_on:
      - "asterisk"
    volumes:
      - ./audioserver-config:/app/config
